<Project Sdk="Microsoft.NET.Sdk">

  <!-- Inherits target framework and output settings from samples/Directory.Build.props -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EfCore.StorageEstimator\EfCore.StorageEstimator.csproj" />
  </ItemGroup>

</Project>
